
default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: backend_technical_challenge_development

test:
  <<: *default
  database: backend_technical_challenge_test

production:
  <<: *default
  database: <=% ENV['DATABASE_URL'] %>
  # username: backend_technical_challenge
  # password: <%= ENV['BACKEND_TECHNICAL_CHALLENGE_DATABASE_PASSWORD'] %>
